### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by josgavrui1** [AgoraUS-G1-1617/Frontend#10]
Buenas compañeros de EGC, ¡qué bien nos lo estamos pasando en el proyecto! Bueno, al caso, aun no hemos realizado nada en cuanto a la documentación y creo que es un buen momento para comenzar a mirarlo.

Me gustaría hacer una issue más larga y divertida pero no se me ocurre nada mas que poner, lo siento Agustín, se que leerás esto y te decepcionará,pero mi creatividad está por los suelos.

Un saludo.

**Comment by anddonram** [comment]
Oído cocina, pero por favor, menos buenrollismo y más trabajo.
Por Favor

**Comment by andjimrio** [comment]
UUfff, comprate un Gin-Tonic para no aburrirte. Qué hacemos, ¿una presentación sin más como dijo el primer día de lo que hemos añadido?
