### ISSUE TITLE
Se ha roto la integración con la API simulada

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Frontend#11]
Compañeros de EGC... Nuestra API de recuento simulada...sniff... ha muerto.
Pero solo en parte.
Resulta que estaba refactorizando el código, para lograr al menos conseguir un botón que enlazara a la API de Recuento auténtica, y cuando al fin lo consigo, pues supe que había cambiado varias funciones y los html donde se muestran la información. Por lo tanto, nuestra API, que tenía un esquema diferente, hay que ajustarla al nuevo. Pero, SOLO podemos tocar el router.js de api-recuento, NO el controlador NI los HTML, porque si no, nos quedaríamos en las mismas y nos cargaríamos el que integra con la API externa.

Con las modernas técnicas de resurrección de software enfocadas a API (es decir, tirarse el finde mirando cómo se hacen las queries con MongoDB), es el momento de devolver a la vida a nuestra querida API.
¿Voluntarios?

**Comment by anddonram** [comment]
He decidido que, si la integración con recuento está hecha, esto no es para tanto, así que le bajo la prioridad.

**Comment by agubelu** [comment]
Sería conveniente que echárais un vistazo a la rama development de recuento porque han cambiado cosas.

**Comment by anddonram** [comment]
Dado que veo difícil que esto esté arreglado, que no es prioritario, y que ya podemos conectarnos con la API de recuento externa (incluso en local), podemos decidir si dejamos esto para el próximo hito o para que lo resuelvan el año que viene.
¿Comentarios?

**Comment by andjimrio** [comment]
Y si la eliminamos?? No sé, pero creo que ahora no aporta nada. Si los del año que viene quieren hacer pruebas sin usar a Recuento, que hagan un json a pelo en un fichero y lo lean. ¿No os parece?
Yo lo eliminaría sin más.

**Comment by josgavrui1** [comment]
Yo voto por no eliminarla y dejarla tal y como está, si quieren arreglarla ya tienen parte hecha y si no pues que no la usen, arreglarla toma demasiado tiempo y no es algo prioritario en mi opinión

**Comment by anddonram** [comment]
Yo también abogo por no eliminarla, los del año que viene dudo que tengan la integración con recuento desde el principio (tendrán que desplegarlo y tal), así que les vendrá bien algo que funcione como stub o mock o lo que sea eso.

**Comment by anddonram** [comment]
dicho eso voy a ponerme con ello, que me aburro algo (y tengo que sumar horas jeje)

**Comment by anddonram** [comment]
pues ya esta algo arreglado, respecto de cómo estaba antes
