### ISSUE TITLE
Arreglar cambio de idioma en html de estadísticas

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Frontend#12]
Tras conseguir conectarme con la API de recuento, he llegado a un nuevo problema. Resulta que el html de esta página (estadísticas) se genera con javascript inyectando el html en la tabla. Por tanto, está fuera del alcance del servicio de traducción.

La idea es arreglar el código para que al html estático pueda inyectarse los textos en el idioma escogido, o alguna otra idea que se os ocurra para solucionarlos.

PD: Saludos Agustín. Siento que esta vez te haya decepcionado.

**Comment by andjimrio** [comment]
Por si te sirve, Eva, lo que se me ocurrió es:
Poner como entrada de las funciones los nombres a poner, y que ahí se encargue Angular de cambiarlo.

En plan:

function () {
 asfsdkfjhaskjfas('Número de votos')
}

function(numVotos) {
 asfsdkfjhaskjfas(numVotos)
}

**Comment by anddonram** [comment]
En breve subiremos el fix a este issue. ¡No se lo pierdan!
