### ISSUE TITLE
Visualización incorrecta pie de página

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Frontend#17]
Buenos días chicos,
llevo bastante tiempo viendo que el pie de página no se muestra correctamente. En el único navegador que parece que va bien es en chrome/chromium.

Os dejo capturas de pantalla y más detalles:

![screenshot_20161222_121112](https://cloud.githubusercontent.com/assets/12049827/21423939/0338c4f0-c840-11e6-9f98-144df705bc76.png)

Navegadores:
- Chrome/Chromium OK
- Vivaldi Error
- FIrefox Error

Mi sistema operativo es Linux

**Comment by ManuelLR** [comment]
Os paso el log que me da el navegador Vivaldi por si os ayuda:

[beta.frontend.agoraus1.egc.duckdns.org-1482405911544.log.txt](https://github.com/AgoraUS-G1-1617/Frontend/files/668618/beta.frontend.agoraus1.egc.duckdns.org-1482405911544.log.txt)

Pero os confirmo, falla al tener habilitado AdBlock

**Comment by andjimrio** [comment]
El log es el siguiente, para que no os descargáis el log es :

beta.frontend.agoraus1.egc.duckdns.org/:18 GET https://beta.frontend.agoraus1.egc.duckdns.org/styles/social-share-kit.css net::ERR_BLOCKED_BY_CLIENT
beta.frontend.agoraus1.egc.duckdns.org/:55 GET https://beta.frontend.agoraus1.egc.duckdns.org/scripts/social-share-kit.min.js net::ERR_BLOCKED_BY_CLIENT
DevTools failed to parse SourceMap: https://beta.frontend.agoraus1.egc.duckdns.org/dist/purify.min.js.map
DevTools failed to parse SourceMap: https://beta.frontend.agoraus1.egc.duckdns.org/scripts/angular.min.js.map
DevTools failed to parse SourceMap: https://beta.frontend.agoraus1.egc.duckdns.org/scripts/angular-route.min.js.map
angular.min.js:107 ReferenceError: SocialShareKit is not defined
    at eval (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2:2622), <anonymous>:2:4)
    at eval (<anonymous>)
    at https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2:2622
    at Function.globalEval (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2:2633)
    at m.fn.init.domManip (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:23107)
    at m.fn.init.append (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:20620)
    at m.fn.init.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:22151)
    at m.access (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:3399)
    at m.fn.init.html (https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:4:21736)
    at link (https://beta.frontend.agoraus1.egc.duckdns.org/scripts/angular.min.js:257:30) <div ng-include="footer.url" class="ng-scope">
(anonymous) @ angular.min.js:107
(anonymous) @ angular.min.js:81
ea @ angular.min.js:73
D @ angular.min.js:62
g @ angular.min.js:55
(anonymous) @ angular.min.js:54
(anonymous) @ angular.min.js:56
k @ angular.min.js:60
(anonymous) @ angular.min.js:256
(anonymous) @ angular.min.js:119
$eval @ angular.min.js:133
$digest @ angular.min.js:130
$apply @ angular.min.js:134
g @ angular.min.js:87
T @ angular.min.js:92
w.onload @ angular.min.js:93
angular.min.js:107 pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
(anonymous) @ angular.min.js:107
j @ angular-translate.min.js:6
sanitize @ angular-translate.min.js:6
d.interpolate @ angular-translate.min.js:6
da @ angular-translate.min.js:6
R.instant @ angular-translate.min.js:6
c @ angular-translate.min.js:6
fn @ VM388:4
(anonymous) @ angular.min.js:114
$digest @ angular.min.js:131
$apply @ angular.min.js:134
g @ angular.min.js:87
T @ angular.min.js:92
w.onload @ angular.min.js:93
jquery.js:9836 GET https://apis.google.com/js/platform.js?_=1482405905757 net::ERR_BLOCKED_BY_CLIENT
send @ jquery.js:9836
ajax @ jquery.js:9215
m._evalUrl @ jquery.js:9373
domManip @ jquery.js:5982
append @ jquery.js:5758
(anonymous) @ jquery.js:5884
m.access @ jquery.js:4157
html @ jquery.js:5848
link @ angular.min.js:257
ea @ angular.min.js:73
D @ angular.min.js:62
g @ angular.min.js:55
(anonymous) @ angular.min.js:54
(anonymous) @ angular.min.js:56
k @ angular.min.js:60
(anonymous) @ angular.min.js:256
(anonymous) @ angular.min.js:119
$eval @ angular.min.js:133
$digest @ angular.min.js:130
$apply @ angular.min.js:134
g @ angular.min.js:87
T @ angular.min.js:92
w.onload @ angular.min.js:93

**Comment by josgavrui1** [comment]
Buenas, he estado tratando de reproducir el error que has comentado para poder solucionar el problema viendo si cambiando cosas consigo que se solucione. Sin embargo, he instalado adblock tanto en Firefox como en Vivaldi, que son los casos que mencionas, en Linux y como puedes ver no me aparece el error, ya que tanto las fechas como el texto de los botones aparece sin problemas:
![imagen](https://cloud.githubusercontent.com/assets/22834907/21425784/6cd58550-c84b-11e6-96ae-61ca13f281d9.png)
![imagen](https://cloud.githubusercontent.com/assets/22834907/21425805/84e3de62-c84b-11e6-8665-d188d6ad617d.png)
Me gustaría que me dijeses si hay algún paso o algo que no esté teniendo en cuenta o simplemente se produce el error en tu ordenador solamente, ya que si no puedo reproducir el error va a ser complicado que consiga solucionarlo sin hacer pruebas.

**Comment by ManuelLR** [comment]
Puede que sea por el tema de las listas, en tu navegador veo que no bloquea nada, en el mío me dice que bloquea 3 elementos.

Esta es mi configuración de AdBlockPlus:
![screenshot_20161222_152726](https://cloud.githubusercontent.com/assets/12049827/21428618/384ce05c-c85b-11e6-8085-bbd6b2b9ff54.png)

y por las pruebas que realicé la lista que produce el fallo es "Fanboy's Social Blocking List"

Quizás lo hayáis puesto como algo social en lugar de un botón normal y eso causa el error?

**Comment by agubelu** [comment]
Desde Firefox con uBlock también ocurre el fallo

**Comment by andjimrio** [comment]
José, tú que has conseguido que se reproduzca el error, a lo mejor te puede interesar esto:

[Anti Adblock Script](http://www.tips2secure.com/2016/03/anti-adblock-script.html)

**Comment by josgavrui1** [comment]
Creo que ya está solucionado, si podéis probarlo y confirmármelo os lo agradecería.

**Comment by agubelu** [comment]
Por aquí parece que sí

**Comment by ManuelLR** [comment]
Yo no podré probar hasta mañana, si no respondo recordármelo porfa

**Comment by ManuelLR** [comment]
Ya lo pude probar y va perfecto. Un error menos, ánimo ! !
