### ISSUE TITLE
Enlace a entrar incorrecto

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Frontend#19]
Primero desearos feliz año.

Me gustaría comentaros que el enlace superior que pone "Entrar" no apunta a un lugar correcto puesto que todos los servicios están desplegados bajo agoraus1.egc.duckdns.org

**Comment by anddonram** [comment]
Nos pondremos en breve con ello, si mal no recuerdo debería apuntar a autenticación, ¿me equivoco?
Saludos y feliz año

**Comment by ManuelLR** [comment]
No podría decirte como debe estar, solo se que no debería apuntar a esa URL

**Comment by anddonram** [comment]
ya se cambió la URL, por favor compruébelo en nuestra beta. Cuando pasemos a master cerraremos la incidencia.
