### ISSUE TITLE
Hay un montón de código innecesario

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Frontend#2]
Saludos otra vez,
mientras estaba comprendiendo el código del año pasado, he visto que hay muchas funciones, controladores y ficheros html que no están siendo usados, están comentados o no se permite el acceso a través del navegador (como por ejemplo, el welcome/index.do)
Por tanto solicito una versión más limpia que elimine todo el código innecesario en aras de poder trabajar con la funcionalidad real del sistema

**Comment by renato-rg** [comment]
Una versión más limpia se ha subido a la rama legacy.
