### ISSUE TITLE
¿Cómo descargar todas las ramas?

### ISSUE THREAD

**Issue by andjimrio** [AgoraUS-G1-1617/Frontend#5]
He estado intentado durante algunos días descargar todas las ramas y no he podido. ¿Sabéis como hacerlo?

**Comment by andjimrio** [comment]
Creo que lo he conseguido, empiezo desde el principio:

`git clone https://github.com/AgoraUS-G1-1617/Frontend.git`
Una vez aquí, nos metemos en la carpeta Frontend
```
git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
git fetch --all
git pull --all
```

**Comment by anddonram** [comment]
estoy seguro que era mucho más facil que eso, porque a mi me paso igual y no he tenido que hacerlo.
No me acuerdo bien, pero creo que me fui en dev al commit origin, y así ya podia hacer pull, pero no estoy seguro

**Comment by andjimrio** [comment]
Ya se!


`git clone`
`git pull --all`
