### ISSUE TITLE
Despliegue con https no seguro

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Frontend#6]
Hola, al acceder a vuestra aplicación me comenta que no carga todo el código y si activo la carga del código se convierte en un sitio inseguro:

![antes de aceptar](https://cloud.githubusercontent.com/assets/12049827/20577817/62bc344e-b1c4-11e6-8488-0a27dda1bd97.png)

![tras aceptar](https://cloud.githubusercontent.com/assets/12049827/20577816/62bbffb0-b1c4-11e6-9e34-f3529c65f625.png)

Posiblemente sea porque hacéis alguna petición a alguna url sin https o similar.

**Comment by andjimrio** [comment]
b54f3ecd9e7675185b47869b08086afaa8d9509c
