### ISSUE TITLE
No hay definido proceso de incidencias en condiciones!

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Frontend#7]
Saludos,
¿pero esto qué es?, si bien se hizo una plantilla  para la gestión de incidencias, ¡esta no define las prioridades y estados de las incidencias! Por favor, mejorad eso y llevad a cabo un proceso de incidencias

**Comment by anddonram** [comment]
Saludos,
no hace falta ser tan directo, ya estamos en ello.

**Comment by anddonram** [comment]
Muy bien, tras un intenso tiempo de trabajo te traemos la gestión de incidencias.
Como has podido ver, lo primero que hemos hecho ha sido marcar el tipo de incidencia que hay: tenemos varios tipos
-example: para ejemplos de cómo resolver incidencias
-bug: para informar de un error en el funcionamiento del código
-enhancement: para proponer una nueva funcionalidad
-help wanted y question: para dudas sobre el funcionamiento en general
tu incidencia es de ejemplo, así que la hemos marcado con esa etiqueta

**Comment by anddonram** [comment]
A continuación, tenemos el asunto de las prioridades. Hay tres etiquetas de alta, media y baja prioridad. La actual es de alta prioridad.
Esto se complementa con las etiquetas de duplicate, invalid y wontfix, que indican, explicación previa, que la incidencia no es válida y no se va a resolver. Se procederá a cerrar la incidencia inmediatamente.
Por último, el estado de la incidencia se marca con solo dos etiquetas: 
-started: indica que se ha tenido en cuenta la incidencia y se está trabajando para resolverla
-fixed: indica que la incidencia ha sido resuelta y verificada. Se espera confirmación del usuario que indicó la incidencia para que compruebe que realmente el problema está resuelto.
Si es así, se puede cerrar la incidencia.
En caso contrario, se debe volver a marcar la etiqueta started.
Como es natural. NO se puede cerrar un issue que esté en estado started, sino que debe pasar a fixed, duplicate, invalid o wontfix (siempre con explicación previa) antes de poder cerrarse.

**Comment by anddonram** [comment]
Muchas gracias por la descripción del proceso, ya puede cerrar

**Comment by andjimrio** [comment]
Jajajajajajajajajajajajajajajaja, y esa motivación?????
