### ISSUE TITLE
Añadir integración con redes sociales

### ISSUE THREAD

**Issue by anddonram** [AgoraUS-G1-1617/Frontend#8]
¿Qué tal, me echabais de menos? Ahora que quedó zanjado el asunto de la gestión de incidencias, vengo con una nueva propuesta.
Dado que tenemos que meterle cosas, y la internacionalización ya está integrada, ¿qué tal si le metemos redes sociales? Estaría bien meterle un par de botones 'like' para poder hacer propaganda del sistema.
Dejo esto en manos de andjimrio, que ya tiene experiencia en este tipo de funciones con JavaScript desde la asignatura de AISS.
Saludos!

**Comment by andjimrio** [comment]
JAjajajajaja, personajeeee!!!

**Comment by andjimrio** [comment]
Después de sangre, sudor y... bueno la verdad es que solo tiempo, aquí va, jefe. Lo he conseguido con esta página:

http://socialsharekit.com/

**Comment by andjimrio** [comment]
89f7dfd21bcd1fda84940cbc13b33495263162f8

**Comment by andjimrio** [comment]
89f7dfd21bcd1fda84940cbc13b33495263162f8
