### ISSUE TITLE
Completar la integración con Recuento

### ISSUE THREAD

**Issue by andjimrio** [AgoraUS-G1-1617/Frontend#9]
Hola equipo, ¿cómo estáis? Yo bien, gracias. Estaba aquí haciendo las prácticas de ASC (uuff!! no sabéis lo bien que me lo estaba pasando haciendo capturas de pantallas) y pensé:
-- MMM, ¿y si integramos el módulo de recuento con nuestro aplicación?
Y como me pareció buena idea, me dije: 
-- Andrés, estoy hay que ponerlo en un issue de Github.

Y por eso escribo esto. Por eso os dejo los link que os pudieran hacer falta. Creo que se puede encargar José Gavilán, por su manejo del recuento de votos.
- Link estable de Recuento: (https://recuento.agoraus1.egc.duckdns.org)
- Documentación de la API: (https://github.com/AgoraUS-G1-1617/Recuento-y-modificacion#peticiones-a-la-api-rest)

Recuerdos a josgavrui1, te deseo lo mejor!!

**Comment by anddonram** [comment]
La verdad es que sí, fue muy buena idea, y hacer capturas de pantalla es muy divertido.
Ya está José a full con esto. Acaba de descubrir el puerto seguro de la API.

**Comment by agubelu** [comment]
Me alegra ver que os lo estáis pasando pipa con ASC. Si necesitáis cualquier cosa nos dejáis una issue.

**Comment by anddonram** [comment]
Más integración. Más AgoraUS

**Comment by anddonram** [comment]
A falta de que terminen el método de recuento (que es precisamente de lo que se encargaban), ya está la integración con el resto de métodos necesarios

**Comment by agubelu** [comment]
Para el martes que viene, a más tardar, estará listo el método de recuento y se solicitará el paso a Master.

**Comment by anddonram** [comment]
Bueno, en breve subiremos los cambios que completan la integración con recuento

**Comment by anddonram** [comment]
Comprobad que efectivamente, podéis coger ver las encuestas de recuento, estadísticas y el mapa
